name: Build and Release

on:
  push:
    branches:
      - main
      - release
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Android SDK prerequisites
        run: |
          python3 scripts/install_minimum_android_sdk_prerequisites.py
          echo "ANDROID_HOME=$HOME/git/syncthing-android-prereq" >> $GITHUB_ENV
          echo "$HOME/git/syncthing-android-prereq/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/git/syncthing-android-prereq/platform-tools" >> $GITHUB_PATH
      
      - name: Get version info
        id: version
        run: |
          VERSION=$(grep 'version-name = ' gradle/libs.versions.toml | cut -d '"' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          COMMIT_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "COMMIT_SHORT=$COMMIT_SHORT" >> $GITHUB_ENV
          echo "commit_short=$COMMIT_SHORT" >> $GITHUB_OUTPUT
      
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Build native Syncthing
        run: ./gradlew --no-daemon buildNative
      
      - name: Build debug APK
        if: github.ref_type != 'tag'
        run: |
          ./gradlew --no-daemon lintDebug assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/syncthing-fork-debug-v${{ env.VERSION }}-${{ env.COMMIT_SHORT }}.apk
      
      - name: Build release APK
        if: github.ref_type == 'tag'
        run: |
          ./gradlew --no-daemon lintRelease assembleRelease
          # Check for both signed and unsigned APK names
          if [ -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
            mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/syncthing-fork-release-v${{ env.VERSION }}.apk
          elif [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
            mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/syncthing-fork-release-v${{ env.VERSION }}.apk
          fi
      
      - name: Upload debug APK artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: syncthing-fork-debug-v${{ env.VERSION }}-${{ env.COMMIT_SHORT }}
          path: app/build/outputs/apk/debug/syncthing-fork-debug-v${{ env.VERSION }}-${{ env.COMMIT_SHORT }}.apk
      
      - name: Upload release APK artifact
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: syncthing-fork-release-v${{ env.VERSION }}
          path: app/build/outputs/apk/release/syncthing-fork-release-v${{ env.VERSION }}.apk
      
      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: app/build/reports/
      
      - name: Create Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          name: Syncthing-Fork ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
          files: |
            app/build/outputs/apk/release/syncthing-fork-release-v${{ env.VERSION }}.apk
          body: |
            ## Syncthing-Fork ${{ github.ref_name }}
            
            ### Downloads
            - [syncthing-fork-release-v${{ env.VERSION }}.apk](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/syncthing-fork-release-v${{ env.VERSION }}.apk)
            
            ### Installation
            1. Download the APK file
            2. Enable "Install from unknown sources" in your Android settings
            3. Install the APK
            
            ### Changes
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/wiki/CHANGELOG.md) for detailed changes.
            
            ### Note
            This is an unsigned APK. You may need to uninstall the previous version before installing this one.